name = "dnextrouter"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespace Binding
[[kv_namespaces]]
binding = "KV"
id = "98a457510d3e4eb99ac9e88a3d4e4303"
